### ISSUE TITLE
Didn't apply the annotation on pdf

### ISSUE THREAD

**Issue by imvikaskohli** [highkite/pdfAnnotate#12]
![image](https://user-images.githubusercontent.com/23357854/96547895-7de84580-12ca-11eb-97e5-ef67d647ffbd.png)
I download the code and try to check the annotation too, it won't work, when I click on any annotation example Square Annotation and then I click on pdf and trying to draw square but didn't do any such annotation, in fact, none of this is working.
is there any jsfiddle or stackblitz or codepen working example of that so I can check and implement that.
Thanks, hope for the positive response

**Comment by waspinator** [comment]
I just gave it a try. While the annotations don't show up in the editor, they are saved into the pdf when you download. Try adding some annotations and then clicking on the "Download" button and viewing the result.

**Comment by imvikaskohli** [comment]
If it's not showing in the editor then how the user will know they successfully annotate the pdf

**Comment by waspinator** [comment]
They'll have to download the PDF to see the annotations. This is either a bug or a missing feature of the editor example, but it is applying the annotation on the pdf. You may want to rename your issue to make it easier for people working on the project to understand what's going wrong.

**Comment by stenvala** [comment]
So is there anyone who managed to make the annotations appear in pdfjs rendered pdf? I didn't find a way. If this is possible, what about e.g. during typing?

**Comment by shmert** [comment]
I ran into this also. `annotationFactory.createTextAnnotation(0, [50, 50, 80, 80], 'Default annotation', 'Sam')` adds an annotation. I can download it. It doesn't show up in the pdf.js renderer. 

I tried refreshing the pdf.js renderer with the modified pdf bytes

```
const annotatedBytes = annotationFactory.write();
pdfObj = await pdfjsLib.getDocument({data: annotatedBytes}).promise;
```

but pdf.js seems to aggressively hold onto its cached version of the file, probably because the fingerprint is the same for both. If there were a way to modify the fingerprint of the PDF on saving, or perhaps invalidate the cached pdf.js that might allow this, but I don't see a way to do that currently.
