### ISSUE TITLE
Annotation of PDF reversed completely

### ISSUE THREAD

**Issue by boneslashXO** [highkite/pdfAnnotate#15]
Hey I just tried to annotate this public document on this website : [Nasa Flight Plan](https://www.hq.nasa.gov/alsj/a17/A17_FlightPlan.pdf)
However everything I tried to annotate is upside down (annotation somewhere else than I clicked + reversed annotation -> attachment). No problem with the annotations on the PDF with the text which is selectable, any ideas? 
![PDFexample](https://user-images.githubusercontent.com/75615990/101490035-12356700-3962-11eb-8549-c020d3cdd45c.png)
EDIT: I just noticed the version of pdf is 1.4 maybe the reported issue is like the issue from the last year #4? 
Adobe reader shows non rotated content popup but still in totally different location

**Comment by highkite** [comment]
Is fixed with version 1.0.14. The flightplan PDF is somewhat unusual since the viewpane is rotated by 180 degrees. With introduction of the `annotationFlags` you can configure the `noRotate` option. This is a default configuration for TextAnnotations (as defined by the standard). For others you can set those manually.
