### ISSUE TITLE
Annotation contents are all empty

### ISSUE THREAD

**Issue by handofthecode** [highkite/pdfAnnotate#37]
I created a pdf document with ms word. The text is all selectable in the pdf, so that text should all be annotations right?
I was not able to get any of the annotations contents this way.

```
const pdfAnnotate = async () => {
  let factory = await AnnotationFactory.loadFile(briefSource);
  let all = await factory.getAnnotations();
  all.forEach((as: Annotation[]) => {
    as.forEach((a: Annotation) => {
      console.log("Annotation string: ", a.contents);
    })
  })
};
```

Thanks for your help!

**Comment by highkite** [comment]
Hello @handofthecode,
what do you mean by "the text is all selectable in the pdf so that text should all be annotations"?

Annotations are for instance those yellow boxes,  that are often rendered similar to sticky notes. On the landing page of the repo you find examples of annotations if you scroll down.

Best,
